Vagrant.configure("2") do |config|
    # The Packer box we just added
    config.vm.box = "kafl_windows"
    # our box name in libvirt
    config.vm.define "vagrant-kafl-windows"

    # rsync doesn't work on WinRM
    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.provider :libvirt do |libvirt|
        # the qcow will be owned by the user
        # so kafl can use the VM's qcow as well
        libvirt.uri = "qemu:///session"
        # spice is better than VNC (mouse handling)
        libvirt.graphics_type = "spice"
        libvirt.cpus = 4
        libvirt.memory = 4096
    end
end
